parser: "@typescript-eslint/parser"
plugins:
  - "@typescript-eslint"
  - prettier
  - simple-import-sort
  - import
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:react/recommended
  - prettier
  - plugin:prettier/recommended
  - plugin:import/typescript

settings:
    react:
      createClass: "createReactClass"
      pragma: "React"
      version: "detect"

rules:
  "@typescript-eslint/member-delimiter-style":
      - error
      - multiline:
          delimiter: none
          requireLast: true
        singleline:
          delimiter: semi
          requireLast: false
  "@typescript-eslint/explicit-function-return-type": 0
  comma-dangle:
    - error
    - always-multiline
  eqeqeq:
    - error
    - always
    - null: ignore
  indent: [error, 4]
  no-console:
    - warn
    - allow: ["warn", "error"]
  react/prop-types: 0
  semi: [error, never]
  simple-import-sort/sort: error
  sort-keys:
    - error
    - asc
    - natural: true
      minKeys: 5
