# Generated by Django 3.0.6 on 2020-06-17 11:15

# Django imports
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RepoApp",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="application.Application",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="repository", name="application",),
        migrations.AlterField(
            model_name="repositoryintvalue",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_int_set",
                to="application.Repository",
            ),
        ),
        migrations.AlterField(
            model_name="repositorystringvalue",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_string_set",
                to="application.Repository",
            ),
        ),
        migrations.AlterField(
            model_name="repositorytextvalue",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_text_set",
                to="application.Repository",
            ),
        ),
        migrations.CreateModel(
            name="RepoAppTextValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=55)),
                ("value", models.TextField()),
                (
                    "repo_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_text_set",
                        to="application.RepoApp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepoAppStringValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=55)),
                ("value", models.CharField(max_length=255)),
                (
                    "repo_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_string_set",
                        to="application.RepoApp",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RepoAppIntValue",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=55)),
                ("value", models.IntegerField()),
                (
                    "repo_app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_int_set",
                        to="application.RepoApp",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="repoapp",
            name="repository",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="application.Repository"
            ),
        ),
        migrations.AddField(
            model_name="repository",
            name="applications",
            field=models.ManyToManyField(
                through="application.RepoApp", to="application.Application"
            ),
        ),
        migrations.AddIndex(
            model_name="repoapptextvalue",
            index=models.Index(
                fields=["repo_app", "key"], name="application_repo_ap_def6e1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repoappstringvalue",
            index=models.Index(
                fields=["repo_app", "key"], name="application_repo_ap_1edee2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="repoappintvalue",
            index=models.Index(
                fields=["repo_app", "key"], name="application_repo_ap_b38bce_idx"
            ),
        ),
    ]
