# Generated by Django 3.0.6 on 2021-02-16 14:04

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("application", "0002_auto_20200617_1115"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="release_branch",
            field=models.CharField(default="main", max_length=50),
        ),
    ]
