# Generated by Django 3.0.6 on 2020-12-30 13:54

# Standard Library
import uuid

# Django imports
from django.db import migrations, models


def create_uuid(apps, schema_editor):
    FileInfo = apps.get_model("version_manager", "fileinfo")
    for fi in FileInfo.objects.all():
        fi.uuid = uuid.uuid4()
        fi.save()


class Migration(migrations.Migration):

    dependencies = [
        ("version_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fileinfo", name="uuid", field=models.UUIDField(null=True),
        ),
        migrations.RunPython(create_uuid),
        migrations.AlterField(
            model_name="fileinfo",
            name="uuid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True, null=False
            ),
        ),
        migrations.AddIndex(
            model_name="fileinfo",
            index=models.Index(fields=["uuid"], name="version_man_uuid_7e8179_idx"),
        ),
    ]
