# Generated by Django 3.0.6 on 2021-02-16 14:04

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("version_manager", "0002_auto_20201230_1354"),
    ]

    operations = [
        migrations.AddField(
            model_name="build",
            name="branch",
            field=models.CharField(default="main", max_length=255),
        ),
    ]
