# Generated by Django 3.0.6 on 2021-02-16 14:04

# Django imports
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("deployment", "0002_auto_20200617_1115"),
    ]

    operations = [
        migrations.AlterField(
            model_name="configenvironment",
            name="environment",
            field=models.SmallIntegerField(
                choices=[(0, "Development"), (1, "Staging"), (2, "Production")]
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="environment",
            field=models.SmallIntegerField(
                choices=[(0, "Development"), (1, "Staging"), (2, "Production")]
            ),
        ),
    ]
